version: "3"
services:
  myapp:
    image: bloodbank:1.5
    build: .
    volumes:
      - ./static_root:/vol/static
    ports:
      - "8002:8002"
    
  nginx:
    image: nginx:latest  # Use the latest Nginx image
    build:
      context: .
      dockerfile: nginx-dockerfile
    volumes:
      - ./static_root:/vol/static  # Mount static files directly into Nginx's default HTML directory
    ports:
      - "84:84"  # Expose Nginx on port 82
