version: "3"
services:
  myapp:
    image: bloodbank:1.5
    build: .
    volumes:
      - static_volumes:/usr/src/app/static_root
    ports:
      - "8002:8002"
  nginx:
    image: nginx
    build: .
      dockerfile: dockerfile
    volumes:
      - static_volumes:/usr/src/app/static_root
volumes:
  static_volumes:
