version: "3"
services:
  myapp:
    image: bloodbank:1.0
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_own_network
    volumes:
      - db-data:/bloodbank/data

networks:
  my_own_network:

volumes:
  db-data:
