version: "3"
services:
  myapp:
    image: bloodbank:1.5
    build: .
    volumes:
      - static_volumes:/usr/src/app/static_root
    ports:
      - "8002:8002"
  nginx:
    image: nginx:latest  # Use the latest Nginx image
    volumes:
      - static_volumes:/usr/share/nginx/html  # Mount static files directly into Nginx's default HTML directory
    ports:
      - "82:80"  # Expose Nginx on port 82
volumes:
  static_volumes:
