version: "3"
services:
  myapp:
    image: bloodbank:1.5
    build: .
    volumes:
      - static_volumes:/usr/src/app/static_root
    ports:
      - "8002:8002"
  nginx:
    image: nginx:1.1
    build:
      context: .
      dockerfile: nginx-dockerfile  
    volumes:
      - static_volumes:/usr/src/app/static_root
    ports:
      - "443:443"
volumes:
  static_volumes:
