version: "3"
services:
  myapp:
    image: bloodbank:1.5
    build: .
    volumes:
      - static-data:/vol/static
  nginx:
    image: nginx:latest  # Use the latest Nginx image
    build: .
    volumes:
      - static-data:/vol/static  # Mount static files directly into Nginx's default HTML directory
    ports:
      - "83:83"  # Expose Nginx on port 82
volumes:
  static-data:
